"""add category

Revision ID: 94274cd2ca38
Revises: 9cfb5783bd22
Create Date: 2026-07-24 20:47:55.197457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94274cd2ca38'
down_revision: Union[str, Sequence[str], None] = '9cfb5783bd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###
