"""make image_url not nullable

Revision ID: 9b1860689bfa
Revises: f100797ae75f
Create Date: 2026-07-27 00:27:51.401474

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9b1860689bfa'
down_revision: str | Sequence[str] | None = 'f100797ae75f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
