"""Update embedding dimension to 384

Revision ID: 9e037f67f9ef
Revises: 0c7e61a30c1b
Create Date: 2026-08-11 11:52:30.317561

"""
from collections.abc import Sequence

from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9e037f67f9ef'
down_revision: str | Sequence[str] | None = '0c7e61a30c1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, clear existing embeddings since dimension is changing
    op.execute("UPDATE articles SET embedding = NULL WHERE embedding IS NOT NULL")

    op.drop_index(op.f('idx_article_entities_article'), table_name='article_entities')
    op.drop_index(op.f('idx_article_entities_entity'), table_name='article_entities')
    op.alter_column('articles', 'embedding',
               existing_type=Vector(dim=1024),
               type_=Vector(dim=384),
               existing_nullable=True)
    op.create_index(op.f('ix_entities_normalized_name'), 'entities', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_normalized_name'), table_name='entities')
    op.alter_column('articles', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=1024),
               existing_nullable=True)
    op.create_index(op.f('idx_article_entities_entity'), 'article_entities', ['entity_id'], unique=False)
    op.create_index(op.f('idx_article_entities_article'), 'article_entities', ['article_id'], unique=False)
    # ### end Alembic commands ###
