"""create summaries table

Revision ID: c33e97df0b14
Revises: 4d53b233cfd0
Create Date: 2026-07-26 12:00:21.380452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33e97df0b14'
down_revision: Union[str, Sequence[str], None] = '4d53b233cfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('key_takeaways_json', sa.Text(), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
