"""add guest_id to conversations

Revision ID: e31fb43ef513
Revises: 5d8e680f800c
Create Date: 2026-07-31 22:04:43.370160

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e31fb43ef513'
down_revision: str | Sequence[str] | None = '5d8e680f800c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('guest_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conversations_guest_id'), 'conversations', ['guest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_guest_id'), table_name='conversations')
    op.drop_column('conversations', 'guest_id')
    # ### end Alembic commands ###
