"""make image_url not nullable

Revision ID: f100797ae75f
Revises: 9c90872457f9
Create Date: 2026-07-27 00:27:09.544646

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f100797ae75f'
down_revision: str | Sequence[str] | None = '9c90872457f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('articles', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index(op.f('ix_articles_feed_types'), table_name='articles')
    op.create_index(op.f('ix_articles_popularity_score'), 'articles', ['popularity_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_popularity_score'), table_name='articles')
    op.create_index(op.f('ix_articles_feed_types'), 'articles', ['feed_types'], unique=False)
    op.alter_column('articles', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
